title: X-Sketchbook - Publishing and Place
description: It's a book! It's an experimental workflow! Released in sections during '21, this publication will be a view on the state of the art of experimentation in architectural publishing
tags:
  - semantic publishing
  - architecture
  - publishing
  - book
  - computational publishing
  - data science
plugins:
  - jekyll-seo-tag
twitter:
  username: mrchristian99
