title: X-Sketchbook &#58; Publishing and Place
description: It&#8217;s a book! It&#8217;s an experimental workflow! Released in sections during &#8217;21, this publication will be a view on the state of the art of experimentation in architectural publishing
tags:
  - semantic publishing
  - architecture
  - publishing
  - book
  - computational publishing
  - data science
plugins:
  - jekyll-seo-tag
twitter:
  username: mrchristian99
