remote_theme: minicomp/ed
title: X-Sketchbook - Publishing and Place
description: A book research prototype released over 2021, covering the state of the art of experimentation in architectural publishing
tags:
  - semantic publishing
  - architecture
  - publishing
  - book
  - computational publishing
  - data science
plugins:
  - jekyll-seo-tag
twitter:
  username: mrchristian99
author:
  twitter: mrchristian99
